### ISSUE TITLE
Not clear how to become Developer

### ISSUE THREAD

**Issue by northys** [safing/docs#25]
It would be nice if there was a note about how to enable "Developer" UI. It always takes me some time to figure out why I do not see the option I'm trying to set. Maybe the pink badge "Developer" could be a link to some one-twitter-length page that describes how to become a developer. Not sure if it's the right place but I tried to click it.

Hmm now I imagined the documentation with link that opens portmaster dashboard at the required settings 😍 

https://docs.safing.io/portmaster/settings#core/log/level

Since I have enabled dev mode already I'll need it again after next reinstall in about a year :D So it's nothing I couldn't live with :D

**Comment by northys** [comment]
🤣 it's mentioned @ page start

**Comment by davegson** [comment]
Yeah the explanations at the top do not help when scrolling through the items. Might improve this at some point to maybe show the text from above when hovering over a tag. But currently, energy is invested elsewhere, so may take a while.

> Hmm now I imagined the documentation with link that opens portmaster dashboard at the required settings 😍

this however is something we really want to do in both directions. So you can easily go to the docs from a Portmaster setting and easily open up the correct PM setting from the docs :)

> Since I have enabled dev mode already I'll need it again after next reinstall in about a year :D

😅
